language: java
dist: xenial
services:
  - xvfb
addons:
  firefox: "latest"
script: mvn clean test
before_install:
  - chmod +x /home/travis/build/vaninatobar/FinalDelivery_Automation/driver/geckodriver
